# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0002_auto_20170201_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitat',
            name='telefon',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
    ]
