# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0006_auto_20170201_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitat',
            name='saldo_ajuntament',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entitat',
            name='saldo_final',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='entitat',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
