# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0007_auto_20170201_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitat',
            name='codi',
            field=models.IntegerField(),
        ),
    ]
