# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0008_auto_20170201_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviments',
            name='_import',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='moviments',
            name='conformitat',
            field=models.BooleanField(default=False),
        ),
    ]
